=== nhetzendorfer/INSY_5CHIT/XMLBrowser/XMLBrowser/tv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <!-- Root element -->
  <xs:element name="TVSCHEDULE">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CHANNEL" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BANNER" type="xs:string"/>
              <xs:element name="DAY" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="DATE" type="xs:string"/>

                    <!-- HOLIDAY or one or more PROGRAMSLOT -->
                    <xs:choice maxOccurs="unbounded">
                      <xs:element name="HOLIDAY" type="xs:string"/>
                      <xs:element name="PROGRAMSLOT">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="TIME" type="xs:string"/>
                            <xs:element name="TITLE">
                              <xs:complexType>
                                <xs:simpleContent>
                                  <xs:extension base="xs:string">
                                    <xs:attribute name="RATING" type="xs:string" use="optional"/>
                                    <xs:attribute name="LANGUAGE" type="xs:string" use="optional"/>
                                  </xs:extension>
                                </xs:simpleContent>
                              </xs:complexType>
                            </xs:element>
                            <xs:element name="DESCRIPTION" type="xs:string" minOccurs="0"/>
                          </xs:sequence>
                          <xs:attribute name="VTR" type="xs:string" use="optional"/>
                        </xs:complexType>
                      </xs:element>
                    </xs:choice>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>

            <xs:attribute name="CHAN" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>

      <xs:attribute name="NAME" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== nhetzendorfer/INSY_5CHIT/tvWithDTD.xml
<?xml-stylesheet type="text/xsl" href="Tv.xsl"?>
<!DOCTYPE TVSCHEDULE [
<!ENTITY copyright "©">
]>

<TVSCHEDULE  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="tv.xsd"
    NAME="Kronenzeitung">
    <CHANNEL CHAN="ORF1">
        <BANNER>orf.png</BANNER>
        <DAY>
            <DATE></DATE>
            <PROGRAMSLOT>
                <TIME>20:15</TIME>
                <TITLE>Das Schweigen es Lämmers</TITLE>
                <DESCRIPTION>Sport</DESCRIPTION>
            </PROGRAMSLOT>
        </DAY>
        <COPYRIGHT>&copyright; orf</COPYRIGHT>
    </CHANNEL>
    <CHANNEL CHAN="ORF2">
        <BANNER>orf.png</BANNER>
        <DAY>
            <DATE></DATE>
            <PROGRAMSLOT>
                <TIME>19:30</TIME>
                <TITLE>Pain</TITLE>
                <DESCRIPTION>Psychological</DESCRIPTION>
            </PROGRAMSLOT>
            <PROGRAMSLOT>
                <TIME>19:30</TIME>
                <TITLE>Herbert die Forsetzung</TITLE>
                <DESCRIPTION>Psychological</DESCRIPTION>
            </PROGRAMSLOT>
            <PROGRAMSLOT>
                <TIME>19:30</TIME>
                <TITLE>Herbert</TITLE>
                <DESCRIPTION>Psychological</DESCRIPTION>
            </PROGRAMSLOT>
        </DAY>
    </CHANNEL>
</TVSCHEDULE>
